language: c
sudo: false
dist: xenial
if: NOT tag = stable
script:
    - make
    - cd tests
    - cd ffmpeg ; make init ; cd ..
    - cd systemd ; make init ; cd ..
    - make all
branches:
    except:
        - stable
after_success:
    - cd ..
    - ./.travis.merge_to_stable_maybe.sh
