language: c
os: linux
dist: focal
if: NOT tag = stable

addons:
  apt:
    packages:
    - lcov

before_install:
    - wget https://github.com/cgreen-devs/cgreen/releases/download/1.4.0/cgreen_1.4.0_amd64.deb
    - sudo apt-get install ./cgreen_1.4.0_amd64.deb
    - sudo apt install openjdk-8-jre
    - lcov --version
    - gcov --version
    - gem install coveralls-lcov

script:
    - cd src
    # Separate coverage for unittest to Codecov
    - cd unittests
    - make COVERAGE=--coverage
    - bash <(curl -s https://codecov.io/bash) -X gcovout
    - cd ..
    # Now reset coverage and run everything
    - lcov -q -z -d .
    - touch ../tests/test_uint32_t/.suspended # Suspend one test
    - make GCOV_OPTIONS= ci                   # = unit, build & test (even slow)

branches:
    except:
        - stable

after_success:
    # Coverage for tests to Coveralls
    - lcov -q -d . -c -o coverage.info
    - lcov -q --remove coverage.info '*.mock' '*.tab.c' '/usr/*' -o coverage.info
    - coveralls-lcov coverage.info
    # Move "stable" tag if on master
    - cd ..
    - ./.travis.merge_to_stable_maybe.sh
