language: c
sudo: false
dist: xenial
if: NOT tag = stable
script:
    - make
    - cd tests/ffmpeg ; make init ; cd ..
    - cd tests/systemd ; make init ; cd ..
    - cd tests; make all
branches:
    except:
        - stable
after_success:
    - cd ..
    - ./.travis.merge_to_stable_maybe.sh
