language: c
os: linux
dist: bionic
if: NOT tag = stable

addons:
  apt:
    packages:
    - lcov

before_install:
    - gem install coveralls-lcov
    - wget https://github.com/cgreen-devs/cgreen/releases/latest/download/cgreen_1.2.0_amd64.deb
    - sudo apt-get install ./cgreen_1.2.0_amd64.deb
    - lcov --version
    - gcov --version

script:
    - cd src
    # Bootstrap
    - make -j c-xref.bs
    # For real
    - make -j debug unit
    # Coverage for unittest to Codecov
    #- bash <(curl -s https://codecov.io/bash)
    - cd ..
    # Now reset coverage and run integration tests
    #- find . -name *.gcda -exec rm {} \;
    - cd tests
    - cd ffmpeg ; make init ; cd ..
    - cd systemd ; make init ; cd ..
    - make all
    - cd ..
    # Coverage for tests to Coveralls
    - lcov -q -d src -c -o coverage.info
    - lcov -q --remove coverage.info *.mock -o coverage.info
    - lcov -q --remove coverage.info *.tab.c -o coverage.info
    - coveralls-lcov coverage.info

branches:
    except:
        - stable

after_success:
    # Move "stable" tag if on master
    - ./.travis.merge_to_stable_maybe.sh
