language: c
os: linux
dist: bionic
if: NOT tag = stable

addons:
  apt:
    packages:
    - lcov

before_install:
    - wget https://github.com/cgreen-devs/cgreen/releases/latest/download/cgreen_1.3.0_amd64.deb
    - sudo apt-get install ./cgreen_1.3.0_amd64.deb
    - sudo apt install openjdk-8-jre
    - lcov --version
    - gcov --version
    - gem install coveralls-lcov

script:
    - cd src
    - make ci-unit
    # Separate coverage for unittest to Codecov
    - cd unittests
    - bash <(curl -s https://codecov.io/bash) -X gcovout
    - cd ..
    # Now reset coverage and run everything
    - lcov -q -z -d .
    - make GCOV_OPTIONS= ci                # = unit, build & test
    # Run the slow tests too
    #- cd ../tests
    #- cd ffmpeg ; make init ; cd ..
    #- cd systemd ; make init ; cd ..
    #- make GCOV_OPTIONS= slow
    - make GCOV_OPTIONS= quick
    - cd ..

branches:
    except:
        - stable

after_success:
    # Coverage for tests to Coveralls
    - lcov -q -d . -c -o coverage.info
    - lcov -q --remove coverage.info '*.mock' '*.tab.c' '/usr/*' -o coverage.info
    - coveralls-lcov coverage.info
    # Move "stable" tag if on master
    - ./.travis.merge_to_stable_maybe.sh
