language: c
os:
  - linux
  - osx

jobs:
  allow_failures:
    - os: osx

dist: focal
osx_image: xcode12

if: NOT tag = stable

addons:
  apt:
    packages:
    - lcov

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then ./.travis_install_linux.sh ; fi

script:
    - cd src
    # Separate coverage for unittest to Codecov
    - cd unittests
    - make COVERAGE=--coverage
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash <(curl -s https://codecov.io/bash) -X gcovout ; fi
    - cd ..
    # Now reset coverage and run everything
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then lcov -q -z -d . ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make ci ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make build ; make test ; fi
    - cd ..

branches:
    except:
        - stable

after_success:
    - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then ./.travis_after_success_linux.sh ; fi
