language: c
os: linux
dist: bionic
if: NOT tag = stable

addons:
  apt:
    packages:
    - lcov

before_install:
    - wget https://github.com/cgreen-devs/cgreen/releases/latest/download/cgreen_1.3.0_amd64.deb
    - sudo apt-get install ./cgreen_1.3.0_amd64.deb
    - sudo apt install openjdk-8-jre
    - lcov --version
    - gcov --version
    - gem install coveralls-lcov

script:
    - cd src/unittests
    - make -k debug
    # Separate coverage for unittest to Codecov
    - bash <(curl -s https://codecov.io/bash)
    - cd ..
    # Now reset coverage and run everything
    - lcov -q -z -d .
    - make ci
    - cd ../tests
    - cd ffmpeg ; make init ; cd ..
    - cd systemd ; make init ; cd ..
    # Run the slow tests too
    - make GCOV= slow
    - cd ..

branches:
    except:
        - stable

after_success:
    # Coverage for tests to Coveralls
    - lcov -q -d src -c -o coverage.info
    - lcov -q --remove coverage.info '*.mock' '*.tab.c' '/usr/*' -o coverage.info
    - coveralls-lcov coverage.info
    # Move "stable" tag if on master
    - ./.travis.merge_to_stable_maybe.sh
