language: c
sudo: false
dist: xenial
if: NOT tag = stable

addons:
  apt:
    packages:
    - lcov
    - emacs-nox

before_install:
    - gem install coveralls-lcov
    - wget https://github.com/cgreen-devs/cgreen/releases/latest/download/cgreen_1.2.0_amd64.deb
    - sudo apt-get install ./cgreen_1.2.0_amd64.deb

script:
    - cd src
    - make COVERAGE="--coverage -O0"
    - cd unittests
    - make COVERAGE="--coverage -O0"
    # Use Codecov for unittest coverage
    - bash <(curl -s https://codecov.io/bash) -c
    - cd ../..
    - lcov --zerocounters
    # Now reset coverage and run integration tests
    - cd tests
    - cd ffmpeg ; make init ; cd ..
    - cd systemd ; make init ; cd ..
    - make all
    - cd ..
    # Coverage to Coveralls
    - lcov -d src -c -o coverage.info
    - lcov --remove coverage.info '/usr/*' -o coverage.info
    - coveralls-lcov coverage.info

branches:
    except:
        - stable

after_success:
    # Move "stable" tag if on master
    - ./.travis.merge_to_stable_maybe.sh
